### PR TITLE
[TG-18919] Update junit and add surefire

### PR DESCRIPTION
**Pull request by theaidenfryguy**
Enabling coverage calculations to be created correctly.

### CODE REVIEW

**Review by ahuggett26 — COMMENTED** [review]
Will this impact existing CF/CyF, or just coverage?

**Comment by ahuggett26** [comment]
> Will this impact existing CF/CyF, or just coverage?

Oh wait, this isn't CoreBanking-CF, nevermind 😅

**Review by ahuggett26 — APPROVED** [review]

**Comment by theaidenfryguy** [comment]
QA note: take this project and run dcover create and upload to cover reports and ensure that the coverage is accurate to the code state.

Ie. There should be no manual tests and only diffblue tests.

image

**Review by yumibagge — COMMENTED** [review]
I think the change is good, but maybe branch name could be like `cover-reports-demo` or something like that since this is public repo?

**Comment by theaidenfryguy** [comment]
> I think the change is good, but maybe branch name could be like `cover-reports-demo` or something like that since this is public repo?

@yumibagge I would say it is ok as it does what it says which is to update surefire. Im not sure a cryptic name is needed.

**Review by yumibagge — APPROVED** [review]
QA review 🆗 

https://diffblue.atlassian.net/browse/TG-18918?focusedCommentId=55565

**Pull request merged**
